config/routes.rb
Rails.application.routes.draw do
  root 'words#index'

  get 'wordlist' => 'words#wordlist'

  resources :words
end

app/models/word.rb
class Word < ActiveRecord::Base
	validates :word, presence: true, length: { minimum:2 }
	validates :definition, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
	def index
		@words = Word.all
	end

	def show
		@word = Word.find(params[:id])
	end

	def new
	end

	def edit
		@word = Word.find(params[:id])
	end

	def create
		@word = Word.new(word_params)

		if @word.save
			redirect_to word_path(@word.id)
		else
			render 'new'
		end
	end

	def update
		@word = Word.find(params[:id])

		if @word.update(word_params)
			redirect_to @word
		else
			render 'edit'
		end
	end

	def destroy
		@word = Word.find(params[:id])
		@word.destroy

		redirect_to words_path
	end

	def wordlist
		@words = Word.all
	end


	private 
		def word_params
			params.require(:word).permit(:word, :definition, :form)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<html>
<head>
  <title>Vocablearn</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<nav class="navbar navbar-inverse navbar-static-top">
	
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to 'VocabLearn', words_path, class: "navbar-brand" %>
		</div>

		<div class="collapse navbar-collapse" id="myNavbar">
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to 'Home', words_path %></li>
				<li><%= link_to 'New Word', new_word_path %></li>
				<li><%= link_to 'Word List', '/wordlist' %></li>
				<li><a href="#">About</a></li>
			</ul>
		</div>


	</div>

</nav> <!-- end of navbar -->

<div class="container">
	
	<div class="jumbotron">
		<%= yield %>
	</div>

</div>

<div class="nav navbar-default navbar-fixed-bottom">
	<div class="container">
		<p class="navbar-text">This website is designed and developed by Sanjeet Dasharath.</p>
	</div>
</div> <!-- end of footer -->

</body>
</html>

app/views/words/edit.html.erb
<h2>Edit word definition: </h2>
<br><br>
<%= form_for :word, url: word_path(@word), method: :patch do |f| %>
	<p>
		<%= f.label :word %> <br>
		<%= f.text_field :word %>
	</p> <br>

	<p>
		<%= f.label :definition %> <br>
		<%= f.text_area :definition %> 
	</p>

	<p>
		<%= select(:word, :form, [['Noun', 'Noun'], ['Adjective', 'Adjective'], ['Verb', 'Verb']]) %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/words/index.html.erb
<div>
	<h1>Vocab Learn</h1>
	<h3>Train for a better vocabulary here.</h3>
</div>
<div class="row">
  <div class="col-sm-12">
    <div class="text-center">
    	<%= link_to word_path(@words.first), class: "btn btn-success btn-lg" do %>Start Now
			<span class="glyphicon glyphicon-flag"></span>
    	<% end %>
    </div>
  </div>
</div>

app/views/words/new.html.erb
<h2>Enter a <mark>word</mark> and a <mark>definition</mark>:</h2>
<br><br>
<%= form_for :word, url: words_path do |f| %>
	<p>
		<%= f.label :word %> <br>
		<%= f.text_field :word %>
	</p> <br>

	<p>
		<%= f.label :definition %> <br>
		<%= f.text_area :definition %> 
	</p>

	<p>
		<%= select(:word, :form, [['Noun', 'Noun'], ['Adjective', 'Adjective'], ['Verb', 'Verb']]) %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/words/show.html.erb
<p>
	<kbd><%= @word.word %></kbd>
</p> 
<div class="well">
	<p>
    <span class="small"><i><%= @word.form %></i></span> <br>
    <%= @word.definition %>
	</p>
</div>

<div class="row">
  <div class="col-sm-12">
    <div class="text-center">
      <div class="btn-group btn-group-lg">
    		<%= link_to words_path, class: "btn btn-primary" do %>
					<span class="glyphicon glyphicon-chevron-left"></span>
    		<% end %>
    		<%= link_to words_path, class: "btn btn-primary" do %>
					<span class="glyphicon glyphicon-chevron-right"></span>
    		<% end %>
			</div>
    </div>
  </div>
</div>

app/views/words/wordlist.html.erb
<% @words.each do |word| %>
<kbd><%= word.word %></kbd>
<div class="well well-sm">
	<p class="text-muted">Definition: </p> <br>
	<span class="small"><i><%= word.form %></i></span> <br>
	<%= word.definition %> <br> <br>
	<%= link_to 'edit', edit_word_path(word), class: "small" %> | <%= link_to 'delete', word_path(word), method: :delete, data: { confirm: 'Are you sure?' }, class: "small" %>
</div>
<hr>
<% end %>